export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_OTHER_USER = 'GET_OTHER_USER';
export const GET_ALL_OTHER_USERS = 'GET_ALL_OTHER_USERS';

export const GET_TO_WATCH = 'GET_TO_WATCH';
export const SWITCH_SHOW = 'SWITCH_SHOW';

export const GET_CURRENT_USER_SHOWS = 'GET_CURRENT_USER_SHOWS';
export const GET_OTHER_USER_SHOWS = 'GET_OTHER_USER_SHOWS';
export const GET_USER_FOLLOWING = 'GET_USER_FOLLOWING';
export const GET_OTHER_USER_FOLLOWING = 'GET_OTHER_USER_FOLLOWING';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const ADD_SHOW = 'ADD_SHOW';
export const DELETE_SHOW = 'DELETE_SHOW';
export const CLEAR_DATA = 'CLEAR_DATA';
export const CLEAR_OTHER_USER = 'CLEAR_OTHER_USER';
export const GET_TAGS = 'GET_TAGS';
export const SET_TAGS = 'SET_TAGS';

export const GET_FOLLOWING_RECS = 'GET_FOLLOWING_RECS';

export default {
  ADD_SHOW,
  DELETE_SHOW,
  GET_CURRENT_USER,
  GET_ALL_OTHER_USERS,
  GET_OTHER_USER,
  CLEAR_DATA,
  FOLLOW,
  UNFOLLOW,
  GET_TAGS,
  SET_TAGS,
  GET_CURRENT_USER_SHOWS,
  GET_OTHER_USER_SHOWS,
  GET_USER_FOLLOWING,
  GET_OTHER_USER_FOLLOWING,
  GET_FOLLOWING_RECS,
  CLEAR_OTHER_USER,
  GET_TO_WATCH,
  SWITCH_SHOW,
};
