export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const GET_OTHER_USER = 'GET_OTHER_USER'
export const GET_ALL_OTHER_USERS = 'GET_ALL_OTHER_USERS'

export const GET_TO_WATCH = 'GET_TO_WATCH'
export const GET_SEEN = 'GET_SEEN'
export const SWITCH_SHOW = 'SWITCH_SHOW'
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY'

export const GET_CURRENT_USER_SHOWS = 'GET_CURRENT_USER_SHOWS'
export const GET_OTHER_USER_SHOWS = 'GET_OTHER_USER_SHOWS'
export const GET_USER_FOLLOWING = 'GET_USER_FOLLOWING'
export const GET_OTHER_USER_FOLLOWING = 'GET_OTHER_USER_FOLLOWING'
export const FOLLOW = 'FOLLOW'
export const UNFOLLOW = 'UNFOLLOW'
export const ADD_SHOW = 'ADD_SHOW'
export const DELETE_SHOW = 'DELETE_SHOW'
export const CLEAR_DATA = 'CLEAR_DATA'
export const CLEAR_OTHER_USER = 'CLEAR_OTHER_USER'
export const CHANGE_SHOW_TAGS = 'CHANGE_SHOW_TAGS'
export const GET_USER_TAGS = 'GET_USER_TAGS'
export const GET_ALL_TAGS = 'GET_ALL_TAGS'
export const GET_OTHER_USER_TAGS = 'GET_OTHER_USER_TAGS'
export const CHANGE_USER_TAGS = 'CHANGE_USER_TAGS'
export const GET_MATCHING_RECS = 'GET_MATCHING_RECS'

export const GET_FOLLOWING_RECS = 'GET_FOLLOWING_RECS'
export const LOGGING_OUT = 'LOGGING_OUT'

export const ADD_TO_WATCH_PROVIDERS = 'ADD_TO_WATCH_PROVIDERS'

export default {
  ADD_SHOW,
  CHANGE_SHOW_TAGS,
  GET_USER_TAGS,
  CHANGE_USER_TAGS,
  GET_ALL_TAGS,
  DELETE_SHOW,
  GET_CURRENT_USER,
  GET_ALL_OTHER_USERS,
  GET_OTHER_USER,
  GET_OTHER_USER_TAGS,
  CLEAR_DATA,
  FOLLOW,
  UNFOLLOW,
  GET_CURRENT_USER_SHOWS,
  GET_OTHER_USER_SHOWS,
  GET_USER_FOLLOWING,
  GET_OTHER_USER_FOLLOWING,
  GET_FOLLOWING_RECS,
  CLEAR_OTHER_USER,
  GET_TO_WATCH,
  SWITCH_SHOW,
  LOGGING_OUT,
  CHANGE_COUNTRY,
  GET_SEEN,
  ADD_TO_WATCH_PROVIDERS,
  GET_MATCHING_RECS,
}
