export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SHOWS = 'GET_CURRENT_USER_SHOWS';
export const GET_USERS_FOLLOWING = 'GET_USERS_FOLLOWING';
export const GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS';

export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const SET_USER_FOLLOWING = 'SET_USER_FOLLOWING';
export const SET_UNFOLLOW = 'SET_UNFOLLOW';
export const CREATE_USER = 'CREATE_USER';
export const ADD_USER = 'ADD_USER';

// export const USER_SHOWS_TAGS_STATE_CHANGE = 'USER_SHOW_TAGS_STATE_CHANGE';

export const GET_CURRENT_USER_SINGLE_SHOW = 'GET_CURRENT_USER_SINGLE_SHOW';
export const GET_SINGLE_USER_ONE_SHOW = 'GET_SINGLE_USER_ONE_SHOW';

export const GET_USERS_SHOWS = 'GET_USERS_SHOWS';
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE';

export const CLEAR_DATA = 'CLEAR_DATA';
export const GET_TAGS = 'GET_TAGS';
export const SET_TAGS = 'SET_TAGS';

export default {
  ADD_USER,
  GET_CURRENT_USER,
  GET_CURRENT_USER_SHOWS,
  GET_USERS_FOLLOWING,
  GET_USER_FOLLOWERS,
  GET_SINGLE_USER,
  SET_USER_FOLLOWING,
  SET_UNFOLLOW,
  CREATE_USER,
  // USER_SHOWS_TAGS_STATE_CHANGE,
  // USERS_SHOWS_STATE_CHANGE,
  GET_CURRENT_USER_SINGLE_SHOW,
  GET_SINGLE_USER_ONE_SHOW,
  USERS_DATA_STATE_CHANGE,
  CLEAR_DATA,
  GET_USERS_SHOWS,
  GET_TAGS,
  SET_TAGS,
};
