export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_SHOWS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE';
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE';
export const USER_SHOWS_TAGS_STATE_CHANGE = 'USER_SHOW_TAGS_STATE_CHANGE';

export const USER_SHOW_STATE_CHANGE = 'USER_SHOW_STATE_CHANGE';
export const USERS_SHOW_STATE_CHANGE = 'USERS_SHOW_STATE_CHANGE';

export const USERS_SHOWS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE';
export const USERS_DATA_STATE_CHANGE = 'USERS_DATA_STATE_CHANGE';

export const CLEAR_DATA = 'CLEAR_DATA';
export const GET_TAGS = 'GET_TAGS';
export const SET_TAGS = 'SET_TAGS';

export default {
  USER_STATE_CHANGE,
  USER_SHOWS_STATE_CHANGE,
  USER_FOLLOWING_STATE_CHANGE,
  USER_SHOWS_TAGS_STATE_CHANGE,
  USERS_SHOWS_STATE_CHANGE,
  USERS_DATA_STATE_CHANGE,
  CLEAR_DATA,
  USER_SHOW_STATE_CHANGE,
  USERS_SHOW_STATE_CHANGE,
  GET_TAGS,
  SET_TAGS,
};
